### ISSUE TITLE
sort order of multi run broken

### ISSUE THREAD

**Issue by kuehl** [jzillmann/jmh-visualizer#13]
use case: release 0.7.3 downloaded and docs-folder local unzipped. using a nanohttpd server with two wwwroots, one for jmh-visualizer-docs and the other for some jmh json reports with simplified run1-runX-naming convention. the display order differs sometimes (5%-10% of all forced page reloads) from the url sortorder leading to declined / improved benchmark results.

any idea?

thanks
me

**Comment by jzillmann** [comment]
Hey @kuehl , sorry for late reply.
So if i understand you correctly the general functionality is correct with your way of deployment, but there is some randomness when it comes to sorting ?
And you mean the sorting of the different runs, so lets say run2 comes before run1 ?

Can you provide your run-names so i can experiment with it ?

**Comment by kuehl** [comment]
hi,

i build a sample:

[jmhv.tar.gz](https://github.com/jzillmann/jmh-visualizer/files/2090669/jmhv.tar.gz)

1.  download
1.  unzip
1. `./gradlew run`

browse url and force (F5) page reloads: the report ordering should sometimes change :confused:

**Comment by jzillmann** [comment]
Hey @kuehl think i found the problem and fixed it. Released 0.7.4 with the fix!
Thanks for finding, reporting and providing the sample!

**Comment by kuehl** [comment]
thx for fixing :+1: 
the new version looks good: no more :dancer: dancing :man_dancing: url-parameter.
