### ISSUE TITLE
Support for log-scale

### ISSUE THREAD

**Issue by lemmy** [jzillmann/jmh-visualizer#14]
Especially when two or more results get compared, an optional log-scale for the x-axis of the bar charts would be useful.

**Comment by jzillmann** [comment]
Ok, should be easy to add since the underlying chart framework has support to it: https://github.com/recharts/recharts/issues/305

How would you prefer to have this ? Switch it on a chart basis ? A global switch ? Or any auto-behavior ?

**Comment by lemmy** [comment]
A switch on a per-chart basis works for me.

**Comment by plokhotnyuk** [comment]
The log scale and its basis can be detected from steps how benchmark parameters increases. 

Log axes are handy to compare how algorithms behave in a wide scale.  Here is an example how we use them with static images to compare RTree implementations: https://github.com/Sizmek/rtree2d

**Comment by jzillmann** [comment]
Did some work on this. Its staged on master and will be released with version 0.9.
If you want to preview: 
[JMH Visualizer.zip](https://github.com/jzillmann/jmh-visualizer/files/2300475/JMH.Visualizer.zip)

@plokhotnyuk I guess that would be useful if we switch parameterized benchmarks to line charts, right ?

**Comment by plokhotnyuk** [comment]
yes, if they are parametrized by numbers

**Comment by jzillmann** [comment]
Closing this, will think more about how to display parameterized benchmarks best...
