### ISSUE TITLE
Missing parameter labels/names

### ISSUE THREAD

**Issue by lemmy** [jzillmann/jmh-visualizer#15]
Even though the parameter names are included in the json input, the bar charts only show the parameter values but omit the label (name) (e.g. see http://jmh.morethan.io/?gist=https://gist.githubusercontent.com/lemmy/30cc904814b563d9df33b7aa8640ad07/raw/bf4cd9b48b0bda91a07d7d59d754dd7d78d19464/Randomization-1530197117-39ace79bf.json which should include "numOfElements" and "size"). This makes it unnecessarily hard to decipher a chart.

**Comment by jzillmann** [comment]
Hey @lemmy , thanks for raising the issue. I've added a change to master which will be online with the next release. 

You could preview the change with following offline version:
[JMH Visualizer.htm.zip](https://github.com/jzillmann/jmh-visualizer/files/2267973/JMH.Visualizer.htm.zip)

Just attach your query parameters when loading it: 
```
?gist=https://gist.githubusercontent.com/lemmy/30cc904814b563d9df33b7aa8640ad07/raw/bf4cd9b48b0bda91a07d7d59d754dd7d78d19464/Randomization-1530197117-39ace79bf.json
```

**Comment by jzillmann** [comment]
Now online..
