### ISSUE TITLE
Accept jmh files by URL

### ISSUE THREAD

**Issue by jabrena** [jzillmann/jmh-visualizer#23]
Hi, 

I would like to know if the UI could accept jmh files by the address.

What do you think?

Juan Antonio

**Comment by jzillmann** [comment]
Hey @jabrena , if i understand you correctly the UI already has support for this!
You could call it e.g. with a `source` parameter like this:
```
http://jmh.morethan.io?source=https://gist.githubusercontent.com/jzillmann/7d23b2382911cc434754a23773b06598/raw/1bcad4bb64624d8a2be15114a4eee4c406c3ae95/string-concatenation_jdk7.json
```
There are also the `sources`, `gist` and `gists` parameters... See https://github.com/jzillmann/jmh-visualizer#parameter-reference and let me know if it works for you!

**Comment by jabrena** [comment]
Hi @jzillmann 

Many thanks for the support. It is working for me :)

Cheers
