### ISSUE TITLE
Doesn't work when source URL is a URL shortener

### ISSUE THREAD

**Issue by lemmy** [jzillmann/jmh-visualizer#25]
```http://jmh.morethan.io/?sources=https://raw.githubusercontent.com/tlaplus/tlaplus/master/tlatools/test-benchmark/tlc2/tool/ModuleOverwrites-1531220029-80dc6de2b.json```  is too long but the shortened ```http://jmh.morethan.io/?sources=https://git.io/fjjn2``` won't load.

Don't want to use an external shortener for the full URL to avoid an external dependency.

**Comment by jzillmann** [comment]
Not a expert here, but to me it looks like `https://git.io/fjjn2` doesn't allow cross origin requests: https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fgit.io%2Ffjjn2&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

Why is the not-shortened to long for you ?

**Comment by lemmy** [comment]
Too long to type manually (e.g. when printed on paper).

**Comment by jzillmann** [comment]
Think this is not possible in a rerverless browser app!
