### ISSUE TITLE
Issues building on Windows?

### ISSUE THREAD

**Issue by cliffycheng** [jzillmann/jmh-visualizer#26]
Hi, thanks for creating this! It's great to use to show people the results of various benchmarks without making them look at a bunch of JSON or CLI output :)

I was hoping to play around with this (our team would like to be able to display score percentile information), but I've been having issues building from a fresh clone? Hopefully I'm just doing something dumb, I'm new to the whole npm/modern day web development thing.

I'm on Windows 10 with Nodejs 10.16.3.

My build steps were
```
npm install
npm run build
```

I'm getting this message:
```
$ npm run build

> jmh-visualizer@0.9.2 build C:\dev\jmh-visualizer
> webpack --mode development

Hash: 069b980a70045607657a
Version: webpack 4.35.3
Time: 384ms
Built at: 10/07/2019 11:00:49 PM
               Asset       Size  Chunks             Chunk Names
           bundle.js   4.13 KiB     app  [emitted]  app
favicons/favicon.ico  318 bytes          [emitted]
          index.html   1.13 KiB          [emitted]
         provided.js   2.21 KiB          [emitted]
         settings.js  146 bytes          [emitted]
Entrypoint app = bundle.js
[./javascript/entry.jsx] 308 bytes {app} [built] [failed] [1 error]

ERROR in ./javascript/entry.jsx 12:4
Module parse failed: Unexpected token (12:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| ReactDOM.render(
>     <Provider>
|         <App />
|     </Provider>
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [../node_modules/html-webpack-plugin/lib/loader.js!./index.html] 1.31 KiB {0} [built]
        + 3 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jmh-visualizer@0.9.2 build: `webpack --mode development`
npm ERR! Exit status 2
```

I haven't made any code changes. Any idea what's going on? I did some quick googling, but all of the common fixes (changing webpack.config.js to include babel for jsx, making sure .babelrc has eslint) already seem to be in place.

**Comment by jzillmann** [comment]
Sorry, haven't been on windows for a long time...
Did you had any luck resolving this in the meantime ?
