### ISSUE TITLE
Support multi file gists

### ISSUE THREAD

**Issue by leonard84** [jzillmann/jmh-visualizer#33]
It would be nice if the visualizer would support multi file gists, and treat them as if you've added separate gists.

For that you'd have to query the API to discover if a gist has multiple files https://docs.github.com/en/rest/reference/gists#get-a-gist and also to get the individual file links.

**Comment by jzillmann** [comment]
You have an example for that?

**Comment by leonard84** [comment]
For a gist with multiple files, or for the api access?

**Comment by jzillmann** [comment]
@leonard84 It's in!

**Comment by leonard84** [comment]
@jzillmann just checked it, and it works great, thanks.

**Comment by willhains** [comment]
@jzillmann @leonard84 Has this feature been removed or become broken? It doesn't seem to work. The [example link](http://jmh.morethan.io/?gist=4c9e282fff30b5fa455ae2496acf4e05) in `README.md` only shows the result of one of the files in the gist.

**Comment by jzillmann** [comment]
@willhains Indeed... there was a bug. Thanks for reporting, it should work now!

**Comment by willhains** [comment]
Awesome, thanks!
