### ISSUE TITLE
The order of two input gists is not as specified via URL

### ISSUE THREAD

**Issue by plevart** [jzillmann/jmh-visualizer#35]
When requesting the comparison of two json gists such as this:
https://jmh.morethan.io/?gists=902f4b43519c4f96c7abcd14cdc2d27d,ac490481e3001c710d75d6071c10b23a
...then order of comparison displayed is non-deterministic. Sometimes it honors the order in the URL sometimes it is reversed. If I reload the page it usually gets ordered as specified with URL but not always. This happens on Mozilla Firefox 92.0 on Linux.
It would be nice if order specified via URL would be honored always.

**Comment by jzillmann** [comment]
Should be stable now, thanks for reporting!
