### ISSUE TITLE
Fails on file containing both parameterized and non-parameterized benchmarks

### ISSUE THREAD

**Issue by ablaagaard** [jzillmann/jmh-visualizer#38]
Tries to get the value of params[0][1] when params is null

**Comment by jzillmann** [comment]
Do you have an json result you can share which reproduces this ?

**Comment by ablaagaard** [comment]
Attached a test file. It seems the order is important - it fails when the non-parameterized results come after the parameterized

[results.json.txt](https://github.com/jzillmann/jmh-visualizer/files/8116262/results.json.txt)

**Comment by jzillmann** [comment]
Oh man, I'm really out of the code / mental model..
Anyway, I deployed a hack which should get you past the initial error. Please check it out (make sure it's version 0.9.6).

I think my code assumes that all tests within the class are homogenous (they use the same parameters, or not).
So to be safe I would advise to build your test classes that way!
