### ISSUE TITLE
Support for Docker Image

### ISSUE THREAD

**Issue by anuragagarwal561994** [jzillmann/jmh-visualizer#49]
We can add support for docker image so that this project is deployable and usable easily for the end user in any environment.

**Comment by jzillmann** [comment]
How is this helpful ?
Where do you generate the reports ? On the docker instance ?

**Comment by anuragagarwal561994** [comment]
So for now, this can allow the user to just self host `jmh-visualizer`.

But the scope of the visualizer can be further extended after this to make it more worth installing via docker. For example one can mention a directory to find the reports (say `data`). The UI can display the directory structure and display reports in the UI.

This can then become self sufficient where the benchmarks can be run in docker environment and results are published in a shared volume. jmh-visualizer can then read the directory structure of this shared volume and help the user visualise the data.

As of now I am using similar setup in a `docker-compose.yaml` way where my benchmark runs and puts the result in a volume. Now that volume is shared the visualizer container. Since visualizer container has nginx to host the UI, I can access the report at lets say: `http://localhost?source=http://localhost/reports.json` and this is pretty seamless.

**Comment by jzillmann** [comment]
Thanks for the answer and sorry for the delay in response... It is merged now.

Regarding the React component... Currently don't do active development of the project.
If you want to implement this, feel free. If it's not too crazy I will merge it ;)
