### ISSUE TITLE
Allow usage of gists

### ISSUE THREAD

**Issue by BrainStone** [jzillmann/jmh-visualizer#5]
It would be an insanely cool feature, if this tool could also work with gists. Like when the URL is `https://gist,github.com/xyz/abc` then `http://jmh.morethan.io/xyz/abc` or `http://jmh.morethan.io/gist/xyz/abc` will use the JSON in that gist.

This would be useful for sharing results and automatically creating graphs.

**Comment by jzillmann** [comment]
Interesting idea! Think i will give it a try...

**Comment by jzillmann** [comment]
Hey @BrainStone , just implemented loading from gists and urls:
- http://jmh.morethan.io/?source=https://gist.githubusercontent.com/jzillmann/7d23b2382911cc434754a23773b06598/raw/1bcad4bb64624d8a2be15114a4eee4c406c3ae95/string-concatenation_jdk7.json
- http://jmh.morethan.io/?sources=https://gist.githubusercontent.com/jzillmann/7d23b2382911cc434754a23773b06598/raw/1bcad4bb64624d8a2be15114a4eee4c406c3ae95/string-concatenation_jdk7.json,https://gist.githubusercontent.com/jzillmann/866d39d43b264f507a67368f2313baca/raw/d0ae1502e8c493e6814c83f2df345fecb763c078/string-concatenation_jdk8.json
- http://jmh.morethan.io/?gist=7d23b2382911cc434754a23773b06598
- http://jmh.morethan.io/?gists=7d23b2382911cc434754a23773b06598,866d39d43b264f507a67368f2313baca

HTH and thanks for the idea, think this is also helpful for use in issue trackers & co!

**Comment by BrainStone** [comment]
Thank you!
