### ISSUE TITLE
Cannot use URL from openjdk code review server

### ISSUE THREAD

**Issue by mcimadamore** [jzillmann/jmh-visualizer#52]
I work on OpenJDK, and I'm trying to publish a JMH report using your great tool. I've uploaded my JMH json files here:

https://cr.openjdk.org/~mcimadamore/jdk/8331865/

Ideally, I'd like to pass the two URLs to the visualizer, so that I can then share the resulting page. But I'm not having luck with using such URLs. Using gist works (or uploading locally) - but I wonder if there's a reason as to why the URL function doesn't seem to work? (and, maybe also making sure it's not an issue on our end, e.g. our code review server).

**Comment by mcimadamore** [comment]
See this comment:
https://github.com/openjdk/jdk/pull/19251#issuecomment-2115361171

**Comment by plokhotnyuk** [comment]
> I work on OpenJDK, and I'm trying to publish a JMH report using your great tool. I've uploaded my JMH json files here:
> 
> https://cr.openjdk.org/~mcimadamore/jdk/8331865/
> 
> Ideally, I'd like to pass the two URLs to the visualizer, so that I can then share the resulting page. But I'm not having luck with using such URLs. Using gist works (or uploading locally) - but I wonder if there's a reason as to why the URL function doesn't seem to work? (and, maybe also making sure it's not an issue on our end, e.g. our code review server).

I tried [this](https://jmh.morethan.io/?sources=https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json,https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_01_8331865.json) URL and got following errors in the browser console:

![image](https://github.com/jzillmann/jmh-visualizer/assets/890289/30af780a-f992-4cf9-8019-b2a5130d8ce0)
You can follow [Learn More](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin) links to see a list of possible mitigations

**Comment by mcimadamore** [comment]
Many thanks for getting back to me. I've verified that indeed there are errors on the browser console, and raised the issue to our team in charge of the server configuration. I will update this issue once I know more. Thanks again.

**Comment by plokhotnyuk** [comment]
@jzillmann Johannes, thanks a bunch! Would you mind to open sponsoring for you GitHub account to allow community to support your incredible work?

**Comment by jzillmann** [comment]
Hey @mcimadamore , it's a CORS issue. Because JMH visualizer doesn't have a server and just runs in the browser, it cannot fetch content from servers with a restrictive content policy.

Workaround would be to use a proxy.
You could manually wrap your urls into e.g. CorsProxy (https://corsproxy.io):

So 
`https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json` 
will become 
`https://corsproxy.io/?https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json` and that will be loadable with the visualizer
https://jmh.morethan.io/?source=https://corsproxy.io/?https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json

**Comment by mcimadamore** [comment]
> So
> `https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json`
> will become
> `https://corsproxy.io/?https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json` and that will be loadable with the visualizer
> https://jmh.morethan.io/?source=https://corsproxy.io/?https://cr.openjdk.org/~mcimadamore/jdk/8331865/loop_over_00_baseline.json

Nice trick/workaround - thanks!

**Comment by mcimadamore** [comment]
Closing this issue as it seems related to the configuration of the openjdk server `cr.openjdk.org` more than anything else. The workaround using CorsProxy works.
