### ISSUE TITLE
Data isn't visualized for small values

### ISSUE THREAD

**Issue by BrainStone** [jzillmann/jmh-visualizer#6]
I typically prefer the sample benchmark over the throughput one. However results are usually around below 1 ms/op. The graph then shows all values as zeros. Decimal values should be supportted in graphing!

Example json: https://gist.github.com/BrainStone/1ec997aaf3cbd07ac925bd6e66d9bcfb

**Comment by jzillmann** [comment]
Ya, thats true i added a rounding since for my benchmarks the decimals were just annoying ;)
Question. Would it make sense in your case to switch to the next lower OutputTimeUnit, like microseconds ?

If not i was thinking about something like when the values are bigger then a certain threshold (lets say 10) then do the rounding otherwise don't.

**Comment by BrainStone** [comment]
Generally speaking, why round at all? These small differences might be important and people might not have the possibility or the time (a proper benchmark could take days) to redo the benchmark with a different scale.

**Comment by jzillmann** [comment]
For me the main benefit is of having the visualizer is cutting through the noise and seeing the most important thing as easy as possible by not being distracted by un-important things!
For the scales i worked with so far, decimals were clearly unimportant.
And i understand that the situation is different for you.

Just wanna check if you are aware on changing the unit and if so, what are your reasons!

**Comment by BrainStone** [comment]
I understand that. But regardless if you want to round I'd recommend rounding to sig figs. Like on the graph 2 sig figs should be sufficient and when hovering over the data 4 are a good choice I think.

**Comment by jzillmann** [comment]
Along with the 0.5.1 version i disabled rounding for datasets where each score was below a certain threshold. Please give it a try and let me know how you like it!
