### ISSUE TITLE
Automate local file visualizing flow

### ISSUE THREAD

**Issue by aleksandr-vin** [jzillmann/jmh-visualizer#9]
I've run into use case, when I made the whole process of benchmarking up to creating `jmh-result.json` the only thing missed is that I need to manually drag-n-drop file onto page.

It will be nice to have a possibility to make a URL that will lead page to source json from another resource, like `http://jmh.morethan.io/?results=https%3A%2F%2Fsomesite%2Fjmh-result.json`. Local file can be uploaded to third-party resource and then a link can be used.

**Comment by jzillmann** [comment]
Hi @aleksandr-vin , yeah that sounds similar to https://github.com/jzillmann/jmh-visualizer/issues/5 
I would try to include both, just not sure when i find time for it!

Btw, in case you're using gradle, then u can also use https://github.com/jzillmann/gradle-jmh-report to build the report locally!

**Comment by skjolber** [comment]
As aleksandr-vin, I would be very happy with a simple page displaying just benchmarks - no drag'n drop, menu or sidebar alternatives. 

I have managed to slim down the default template to what I'd like to see: 

https://skjolber.github.io/xml-log-filter/docs/benchmark/jmh/index.html

I guess linking the file via URL parameter is useful, I'd like also to be able to link json files containing links to the benchmark results and perhaps some crude coloring scheme.

**Comment by jzillmann** [comment]
@aleksandr-vin Implemented loading from url...

I've called the parameter 'source' for one url and 'sources' for multiple urls:
- http://jmh.morethan.io/?source=https://gist.githubusercontent.com/jzillmann/7d23b2382911cc434754a23773b06598/raw/1bcad4bb64624d8a2be15114a4eee4c406c3ae95/string-concatenation_jdk7.json
- http://jmh.morethan.io/?sources=https://gist.githubusercontent.com/jzillmann/7d23b2382911cc434754a23773b06598/raw/1bcad4bb64624d8a2be15114a4eee4c406c3ae95/string-concatenation_jdk7.json,https://gist.githubusercontent.com/jzillmann/866d39d43b264f507a67368f2313baca/raw/d0ae1502e8c493e6814c83f2df345fecb763c078/string-concatenation_jdk8.json

(Also added 'gist' and 'gists')

@skjolber I moved your customization requests to https://github.com/jzillmann/jmh-visualizer/issues/12
